<h1 class="text-center text-warning"><?php echo $this->locale->_('component_title');?></h1>
<div class="w-50 m-auto">
<?php

echo $this->tag->form('');
echo '<label for="component" class="form-label">Component Name</label>';
echo $this->tag->textField(["name", 'class'=>"form-control"]);

echo '<label for="actions" class="form-label">Action Name</label>';
echo $this->tag->textField(["actions", 'class'=>"form-control"]);

echo $this->tag->submitButton([$this->locale->_('component_title'), 'class'=>"btn btn-primary mt-3"]);
?>
</div>
<div class="alert alert-danger w-50 m-auto mt-2"><?php if (isset($message)) echo $message; ?></div>
