<h1 class="text-center text-warning">Sign Up</h1>
<div class="w-50 m-auto">
<?php

echo $this->tag->form('');

echo '<label for="name" class="form-label">Name</label>';
echo $this->tag->textField(["name", 'class'=>"form-control"]);

echo '<label for="email" class="form-label">Email</label>';
echo $this->tag->textField(["email", 'class'=>"form-control"]);
?>
<label for="role" class="form-label">Select Role</label>
<select class="form-select" name="role" aria-label="Default select example">
  <option value="" selected></option>
    <?php
        foreach ($roles as $role) {
            echo '<option value="'.$role->id.'">'.$role->name.'</option>';
        }
    ?>
  
</select>

<?php echo $this->tag->submitButton(["SignUp", 'class'=>"btn btn-primary mt-3"]); ?>
</div>
<div class="alert alert-danger w-50 m-auto mt-2"><?php if (isset($message)) echo $message; ?></div>
<div class="alert alert-success w-50 m-auto mt-2 text-break"><?php if (isset($token)) echo $token; ?></div>
